[2024-10-29 14:39:16,946] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-09-30T00:00:00+00:00 [queued]>
[2024-10-29 14:39:16,951] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-09-30T00:00:00+00:00 [queued]>
[2024-10-29 14:39:16,951] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-10-29 14:39:16,951] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-10-29 14:39:16,951] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-10-29 14:39:16,964] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2024-09-30 00:00:00+00:00
[2024-10-29 14:39:16,967] {standard_task_runner.py:52} INFO - Started process 105715 to run task
[2024-10-29 14:39:16,969] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2024-09-30T00:00:00+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpi3118kyf', '--error-file', '/tmp/tmp9zqm2f5g']
[2024-10-29 14:39:16,969] {standard_task_runner.py:80} INFO - Job 30: Subtask cria_pasta
[2024-10-29 14:39:16,997] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-09-30T00:00:00+00:00 [running]> on host LAPTOP-SNAE0A1O.
[2024-10-29 14:39:17,018] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1451, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1555, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2212, in render_templates
    rendered_task = self.task.render_template_fields(context)
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 1185, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/utils/session.py", line 71, in wrapper
    return func(*args, session=session, **kwargs)
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 344, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 387, in render_template
    template = jinja_env.from_string(value)
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1092, in from_string
    return cls.from_code(self, self.compile(source), gs, None)
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/jinja2/environment.py", line 757, in compile
    self.handle_exception(source=source_hint)
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<unknown>", line 1, in template
jinja2.exceptions.TemplateSyntaxError: unexpected '%'
[2024-10-29 14:39:17,025] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20240930T000000, start_date=20241029T173916, end_date=20241029T173917
[2024-10-29 14:39:17,036] {standard_task_runner.py:92} ERROR - Failed to execute job 30 for task cria_pasta (unexpected '%'; 105715)
[2024-10-29 14:39:17,061] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-10-29 14:39:17,081] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-29 14:43:42,515] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-09-30T00:00:00+00:00 [queued]>
[2024-10-29 14:43:42,519] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-09-30T00:00:00+00:00 [queued]>
[2024-10-29 14:43:42,519] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-10-29 14:43:42,519] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-10-29 14:43:42,519] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-10-29 14:43:42,531] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2024-09-30 00:00:00+00:00
[2024-10-29 14:43:42,534] {standard_task_runner.py:52} INFO - Started process 107800 to run task
[2024-10-29 14:43:42,535] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2024-09-30T00:00:00+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmp39i4_hh5', '--error-file', '/tmp/tmpcfpj65g4']
[2024-10-29 14:43:42,535] {standard_task_runner.py:80} INFO - Job 30: Subtask cria_pasta
[2024-10-29 14:43:42,561] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-09-30T00:00:00+00:00 [running]> on host LAPTOP-SNAE0A1O.
[2024-10-29 14:43:42,579] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1451, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1555, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2212, in render_templates
    rendered_task = self.task.render_template_fields(context)
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 1185, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/utils/session.py", line 71, in wrapper
    return func(*args, session=session, **kwargs)
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 344, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 391, in render_template
    return render_template_to_string(template, context)
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/utils/helpers.py", line 296, in render_template_to_string
    return render_template(template, context, native=False)
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/utils/helpers.py", line 291, in render_template
    return "".join(nodes)
  File "<template>", line 13, in root
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/jinja2/sandbox.py", line 326, in getattr
    value = getattr(obj, attribute)
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/jinja2/runtime.py", line 910, in __getattr__
    return self._fail_with_undefined_error()
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/jinja2/runtime.py", line 903, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'date_interval_end' is undefined
[2024-10-29 14:43:42,584] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20240930T000000, start_date=20241029T174342, end_date=20241029T174342
[2024-10-29 14:43:42,594] {standard_task_runner.py:92} ERROR - Failed to execute job 30 for task cria_pasta ('date_interval_end' is undefined; 107800)
[2024-10-29 14:43:42,629] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-10-29 14:43:42,649] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-29 14:46:26,079] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-09-30T00:00:00+00:00 [queued]>
[2024-10-29 14:46:26,084] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-09-30T00:00:00+00:00 [queued]>
[2024-10-29 14:46:26,084] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-10-29 14:46:26,084] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-10-29 14:46:26,084] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-10-29 14:46:26,096] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2024-09-30 00:00:00+00:00
[2024-10-29 14:46:26,099] {standard_task_runner.py:52} INFO - Started process 109113 to run task
[2024-10-29 14:46:26,100] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2024-09-30T00:00:00+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmptczefp8g', '--error-file', '/tmp/tmpwql3_60m']
[2024-10-29 14:46:26,100] {standard_task_runner.py:80} INFO - Job 30: Subtask cria_pasta
[2024-10-29 14:46:26,126] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-09-30T00:00:00+00:00 [running]> on host LAPTOP-SNAE0A1O.
[2024-10-29 14:46:26,144] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1451, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1555, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2212, in render_templates
    rendered_task = self.task.render_template_fields(context)
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 1185, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/utils/session.py", line 71, in wrapper
    return func(*args, session=session, **kwargs)
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 344, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 391, in render_template
    return render_template_to_string(template, context)
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/utils/helpers.py", line 296, in render_template_to_string
    return render_template(template, context, native=False)
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/utils/helpers.py", line 291, in render_template
    return "".join(nodes)
  File "<template>", line 13, in root
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/jinja2/sandbox.py", line 326, in getattr
    value = getattr(obj, attribute)
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/jinja2/runtime.py", line 910, in __getattr__
    return self._fail_with_undefined_error()
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/jinja2/runtime.py", line 903, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'date_interval_end' is undefined
[2024-10-29 14:46:26,147] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20240930T000000, start_date=20241029T174626, end_date=20241029T174626
[2024-10-29 14:46:26,158] {standard_task_runner.py:92} ERROR - Failed to execute job 30 for task cria_pasta ('date_interval_end' is undefined; 109113)
[2024-10-29 14:46:26,193] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-10-29 14:46:26,213] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-29 14:50:13,197] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-09-30T00:00:00+00:00 [queued]>
[2024-10-29 14:50:13,202] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-09-30T00:00:00+00:00 [queued]>
[2024-10-29 14:50:13,202] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-10-29 14:50:13,202] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-10-29 14:50:13,202] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-10-29 14:50:13,213] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2024-09-30 00:00:00+00:00
[2024-10-29 14:50:13,215] {standard_task_runner.py:52} INFO - Started process 110936 to run task
[2024-10-29 14:50:13,216] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2024-09-30T00:00:00+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpf2i0qx7f', '--error-file', '/tmp/tmpvyqlmjoi']
[2024-10-29 14:50:13,217] {standard_task_runner.py:80} INFO - Job 36: Subtask cria_pasta
[2024-10-29 14:50:13,243] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-09-30T00:00:00+00:00 [running]> on host LAPTOP-SNAE0A1O.
[2024-10-29 14:50:13,279] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2024-09-30T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-09-30T00:00:00+00:00
[2024-10-29 14:50:13,280] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-10-29 14:50:13,280] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/root/Documentos/airflow/semana=2024-10-07"']
[2024-10-29 14:50:13,286] {subprocess.py:85} INFO - Output:
[2024-10-29 14:50:13,289] {subprocess.py:96} INFO - Command exited with return code 0
[2024-10-29 14:50:13,305] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20240930T000000, start_date=20241029T175013, end_date=20241029T175013
[2024-10-29 14:50:13,349] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-10-29 14:50:13,368] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-29 14:53:40,620] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-09-30T00:00:00+00:00 [queued]>
[2024-10-29 14:53:40,625] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-09-30T00:00:00+00:00 [queued]>
[2024-10-29 14:53:40,625] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-10-29 14:53:40,625] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-10-29 14:53:40,625] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-10-29 14:53:40,636] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2024-09-30 00:00:00+00:00
[2024-10-29 14:53:40,639] {standard_task_runner.py:52} INFO - Started process 112658 to run task
[2024-10-29 14:53:40,641] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2024-09-30T00:00:00+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmp1gch4y_g', '--error-file', '/tmp/tmpcf0hqn_h']
[2024-10-29 14:53:40,641] {standard_task_runner.py:80} INFO - Job 36: Subtask cria_pasta
[2024-10-29 14:53:40,665] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-09-30T00:00:00+00:00 [running]> on host LAPTOP-SNAE0A1O.
[2024-10-29 14:53:40,700] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2024-09-30T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-09-30T00:00:00+00:00
[2024-10-29 14:53:40,701] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-10-29 14:53:40,701] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/root/Documentos/airflow/semana=2024-10-07"']
[2024-10-29 14:53:40,706] {subprocess.py:85} INFO - Output:
[2024-10-29 14:53:40,708] {subprocess.py:96} INFO - Command exited with return code 0
[2024-10-29 14:53:40,723] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20240930T000000, start_date=20241029T175340, end_date=20241029T175340
[2024-10-29 14:53:40,773] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-10-29 14:53:40,790] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-29 14:56:44,963] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-09-30T00:00:00+00:00 [queued]>
[2024-10-29 14:56:44,968] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-09-30T00:00:00+00:00 [queued]>
[2024-10-29 14:56:44,968] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-10-29 14:56:44,968] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-10-29 14:56:44,968] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-10-29 14:56:44,979] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2024-09-30 00:00:00+00:00
[2024-10-29 14:56:44,982] {standard_task_runner.py:52} INFO - Started process 114197 to run task
[2024-10-29 14:56:44,984] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2024-09-30T00:00:00+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpekio5_4i', '--error-file', '/tmp/tmpdr_b81gb']
[2024-10-29 14:56:44,984] {standard_task_runner.py:80} INFO - Job 36: Subtask cria_pasta
[2024-10-29 14:56:45,011] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-09-30T00:00:00+00:00 [running]> on host LAPTOP-SNAE0A1O.
[2024-10-29 14:56:45,046] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2024-09-30T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-09-30T00:00:00+00:00
[2024-10-29 14:56:45,047] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-10-29 14:56:45,048] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/root/Documentos/airflow/semana=2024-10-07"']
[2024-10-29 14:56:45,053] {subprocess.py:85} INFO - Output:
[2024-10-29 14:56:45,054] {subprocess.py:96} INFO - Command exited with return code 0
[2024-10-29 14:56:45,070] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20240930T000000, start_date=20241029T175644, end_date=20241029T175645
[2024-10-29 14:56:45,116] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-10-29 14:56:45,135] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-29 15:02:39,942] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-09-30T00:00:00+00:00 [queued]>
[2024-10-29 15:02:39,945] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-09-30T00:00:00+00:00 [queued]>
[2024-10-29 15:02:39,946] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-10-29 15:02:39,946] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-10-29 15:02:39,946] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-10-29 15:02:39,957] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2024-09-30 00:00:00+00:00
[2024-10-29 15:02:39,959] {standard_task_runner.py:52} INFO - Started process 117020 to run task
[2024-10-29 15:02:39,961] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2024-09-30T00:00:00+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpqd0722vl', '--error-file', '/tmp/tmpysknavqh']
[2024-10-29 15:02:39,961] {standard_task_runner.py:80} INFO - Job 36: Subtask cria_pasta
[2024-10-29 15:02:39,989] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-09-30T00:00:00+00:00 [running]> on host LAPTOP-SNAE0A1O.
[2024-10-29 15:02:40,024] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2024-09-30T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-09-30T00:00:00+00:00
[2024-10-29 15:02:40,025] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-10-29 15:02:40,025] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/root/Documentos/airflow/semana=2024-10-07"']
[2024-10-29 15:02:40,031] {subprocess.py:85} INFO - Output:
[2024-10-29 15:02:40,033] {subprocess.py:96} INFO - Command exited with return code 0
[2024-10-29 15:02:40,048] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20240930T000000, start_date=20241029T180239, end_date=20241029T180240
[2024-10-29 15:02:40,093] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-10-29 15:02:40,112] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-29 15:05:34,135] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-09-30T00:00:00+00:00 [queued]>
[2024-10-29 15:05:34,139] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-09-30T00:00:00+00:00 [queued]>
[2024-10-29 15:05:34,139] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-10-29 15:05:34,139] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-10-29 15:05:34,139] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-10-29 15:05:34,150] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2024-09-30 00:00:00+00:00
[2024-10-29 15:05:34,153] {standard_task_runner.py:52} INFO - Started process 118495 to run task
[2024-10-29 15:05:34,154] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2024-09-30T00:00:00+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpi1iey1ca', '--error-file', '/tmp/tmpnfot5ly2']
[2024-10-29 15:05:34,155] {standard_task_runner.py:80} INFO - Job 36: Subtask cria_pasta
[2024-10-29 15:05:34,182] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-09-30T00:00:00+00:00 [running]> on host LAPTOP-SNAE0A1O.
[2024-10-29 15:05:34,218] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2024-09-30T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-09-30T00:00:00+00:00
[2024-10-29 15:05:34,219] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-10-29 15:05:34,219] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/root/Documentos/airflow/semana=2024-10-07"']
[2024-10-29 15:05:34,225] {subprocess.py:85} INFO - Output:
[2024-10-29 15:05:34,226] {subprocess.py:96} INFO - Command exited with return code 0
[2024-10-29 15:05:34,241] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20240930T000000, start_date=20241029T180534, end_date=20241029T180534
[2024-10-29 15:05:34,287] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-10-29 15:05:34,305] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-29 15:10:59,296] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-09-30T00:00:00+00:00 [queued]>
[2024-10-29 15:10:59,301] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-09-30T00:00:00+00:00 [queued]>
[2024-10-29 15:10:59,301] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-10-29 15:10:59,301] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-10-29 15:10:59,301] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-10-29 15:10:59,313] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2024-09-30 00:00:00+00:00
[2024-10-29 15:10:59,316] {standard_task_runner.py:52} INFO - Started process 121112 to run task
[2024-10-29 15:10:59,318] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2024-09-30T00:00:00+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmp88vfsh07', '--error-file', '/tmp/tmp5ivggo4_']
[2024-10-29 15:10:59,318] {standard_task_runner.py:80} INFO - Job 36: Subtask cria_pasta
[2024-10-29 15:10:59,346] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-09-30T00:00:00+00:00 [running]> on host LAPTOP-SNAE0A1O.
[2024-10-29 15:10:59,384] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2024-09-30T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-09-30T00:00:00+00:00
[2024-10-29 15:10:59,384] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-10-29 15:10:59,385] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/root/Documentos/airflow/semana=2024-10-07"']
[2024-10-29 15:10:59,390] {subprocess.py:85} INFO - Output:
[2024-10-29 15:10:59,391] {subprocess.py:96} INFO - Command exited with return code 0
[2024-10-29 15:10:59,407] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20240930T000000, start_date=20241029T181059, end_date=20241029T181059
[2024-10-29 15:10:59,450] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-10-29 15:10:59,472] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-29 15:14:24,678] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-09-30T00:00:00+00:00 [queued]>
[2024-10-29 15:14:24,683] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-09-30T00:00:00+00:00 [queued]>
[2024-10-29 15:14:24,683] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-10-29 15:14:24,683] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-10-29 15:14:24,683] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-10-29 15:14:24,694] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2024-09-30 00:00:00+00:00
[2024-10-29 15:14:24,697] {standard_task_runner.py:52} INFO - Started process 122816 to run task
[2024-10-29 15:14:24,698] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2024-09-30T00:00:00+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpzf2onbpw', '--error-file', '/tmp/tmpo2z1jorg']
[2024-10-29 15:14:24,698] {standard_task_runner.py:80} INFO - Job 36: Subtask cria_pasta
[2024-10-29 15:14:24,724] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-09-30T00:00:00+00:00 [running]> on host LAPTOP-SNAE0A1O.
[2024-10-29 15:14:24,763] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2024-09-30T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-09-30T00:00:00+00:00
[2024-10-29 15:14:24,763] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-10-29 15:14:24,763] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/root/Documentos/airflow/semana=2024-10-07"']
[2024-10-29 15:14:24,769] {subprocess.py:85} INFO - Output:
[2024-10-29 15:14:24,770] {subprocess.py:96} INFO - Command exited with return code 0
[2024-10-29 15:14:24,786] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20240930T000000, start_date=20241029T181424, end_date=20241029T181424
[2024-10-29 15:14:24,831] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-10-29 15:14:24,849] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-29 19:04:38,086] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-09-30T00:00:00+00:00 [queued]>
[2024-10-29 19:04:38,091] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-09-30T00:00:00+00:00 [queued]>
[2024-10-29 19:04:38,091] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-10-29 19:04:38,091] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-10-29 19:04:38,091] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-10-29 19:04:38,104] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2024-09-30 00:00:00+00:00
[2024-10-29 19:04:38,107] {standard_task_runner.py:52} INFO - Started process 54186 to run task
[2024-10-29 19:04:38,109] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2024-09-30T00:00:00+00:00', '--job-id', '52', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmp0tvfeflc', '--error-file', '/tmp/tmp3kc2ty9s']
[2024-10-29 19:04:38,109] {standard_task_runner.py:80} INFO - Job 52: Subtask cria_pasta
[2024-10-29 19:04:38,134] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-09-30T00:00:00+00:00 [running]> on host LAPTOP-SNAE0A1O.
[2024-10-29 19:04:38,170] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2024-09-30T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-09-30T00:00:00+00:00
[2024-10-29 19:04:38,171] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-10-29 19:04:38,172] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/root/Documentos/airflow/semana=2024-10-07"']
[2024-10-29 19:04:38,178] {subprocess.py:85} INFO - Output:
[2024-10-29 19:04:38,181] {subprocess.py:96} INFO - Command exited with return code 0
[2024-10-29 19:04:38,196] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20240930T000000, start_date=20241029T220438, end_date=20241029T220438
[2024-10-29 19:04:38,242] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-10-29 19:04:38,259] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
