[2024-10-29 14:39:22,382] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-10-14T00:00:00+00:00 [queued]>
[2024-10-29 14:39:22,385] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-10-14T00:00:00+00:00 [queued]>
[2024-10-29 14:39:22,385] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-10-29 14:39:22,385] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-10-29 14:39:22,385] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-10-29 14:39:22,397] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2024-10-14 00:00:00+00:00
[2024-10-29 14:39:22,400] {standard_task_runner.py:52} INFO - Started process 105781 to run task
[2024-10-29 14:39:22,402] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2024-10-14T00:00:00+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpl94xedir', '--error-file', '/tmp/tmp_0885zvm']
[2024-10-29 14:39:22,403] {standard_task_runner.py:80} INFO - Job 32: Subtask cria_pasta
[2024-10-29 14:39:22,428] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-10-14T00:00:00+00:00 [running]> on host LAPTOP-SNAE0A1O.
[2024-10-29 14:39:22,446] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1451, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1555, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2212, in render_templates
    rendered_task = self.task.render_template_fields(context)
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 1185, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/utils/session.py", line 71, in wrapper
    return func(*args, session=session, **kwargs)
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 344, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 387, in render_template
    template = jinja_env.from_string(value)
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1092, in from_string
    return cls.from_code(self, self.compile(source), gs, None)
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/jinja2/environment.py", line 757, in compile
    self.handle_exception(source=source_hint)
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<unknown>", line 1, in template
jinja2.exceptions.TemplateSyntaxError: unexpected '%'
[2024-10-29 14:39:22,449] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20241014T000000, start_date=20241029T173922, end_date=20241029T173922
[2024-10-29 14:39:22,459] {standard_task_runner.py:92} ERROR - Failed to execute job 32 for task cria_pasta (unexpected '%'; 105781)
[2024-10-29 14:39:22,495] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-10-29 14:39:22,517] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-29 14:43:45,563] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-10-14T00:00:00+00:00 [queued]>
[2024-10-29 14:43:45,567] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-10-14T00:00:00+00:00 [queued]>
[2024-10-29 14:43:45,567] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-10-29 14:43:45,567] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-10-29 14:43:45,567] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-10-29 14:43:45,580] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2024-10-14 00:00:00+00:00
[2024-10-29 14:43:45,582] {standard_task_runner.py:52} INFO - Started process 107863 to run task
[2024-10-29 14:43:45,584] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2024-10-14T00:00:00+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpw8gxwhp5', '--error-file', '/tmp/tmpht017_qe']
[2024-10-29 14:43:45,585] {standard_task_runner.py:80} INFO - Job 32: Subtask cria_pasta
[2024-10-29 14:43:45,611] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-10-14T00:00:00+00:00 [running]> on host LAPTOP-SNAE0A1O.
[2024-10-29 14:43:45,628] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1451, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1555, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2212, in render_templates
    rendered_task = self.task.render_template_fields(context)
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 1185, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/utils/session.py", line 71, in wrapper
    return func(*args, session=session, **kwargs)
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 344, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 391, in render_template
    return render_template_to_string(template, context)
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/utils/helpers.py", line 296, in render_template_to_string
    return render_template(template, context, native=False)
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/utils/helpers.py", line 291, in render_template
    return "".join(nodes)
  File "<template>", line 13, in root
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/jinja2/sandbox.py", line 326, in getattr
    value = getattr(obj, attribute)
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/jinja2/runtime.py", line 910, in __getattr__
    return self._fail_with_undefined_error()
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/jinja2/runtime.py", line 903, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'date_interval_end' is undefined
[2024-10-29 14:43:45,631] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20241014T000000, start_date=20241029T174345, end_date=20241029T174345
[2024-10-29 14:43:45,641] {standard_task_runner.py:92} ERROR - Failed to execute job 32 for task cria_pasta ('date_interval_end' is undefined; 107863)
[2024-10-29 14:43:45,676] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-10-29 14:43:45,696] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-29 14:46:29,883] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-10-14T00:00:00+00:00 [queued]>
[2024-10-29 14:46:29,888] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-10-14T00:00:00+00:00 [queued]>
[2024-10-29 14:46:29,888] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-10-29 14:46:29,888] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-10-29 14:46:29,888] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-10-29 14:46:29,908] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2024-10-14 00:00:00+00:00
[2024-10-29 14:46:29,911] {standard_task_runner.py:52} INFO - Started process 109176 to run task
[2024-10-29 14:46:29,912] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2024-10-14T00:00:00+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpefuzeex_', '--error-file', '/tmp/tmp1tp0ic8e']
[2024-10-29 14:46:29,912] {standard_task_runner.py:80} INFO - Job 32: Subtask cria_pasta
[2024-10-29 14:46:29,937] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-10-14T00:00:00+00:00 [running]> on host LAPTOP-SNAE0A1O.
[2024-10-29 14:46:29,956] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1451, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1555, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2212, in render_templates
    rendered_task = self.task.render_template_fields(context)
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 1185, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/utils/session.py", line 71, in wrapper
    return func(*args, session=session, **kwargs)
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 344, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 391, in render_template
    return render_template_to_string(template, context)
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/utils/helpers.py", line 296, in render_template_to_string
    return render_template(template, context, native=False)
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/utils/helpers.py", line 291, in render_template
    return "".join(nodes)
  File "<template>", line 13, in root
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/jinja2/sandbox.py", line 326, in getattr
    value = getattr(obj, attribute)
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/jinja2/runtime.py", line 910, in __getattr__
    return self._fail_with_undefined_error()
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/jinja2/runtime.py", line 903, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'date_interval_end' is undefined
[2024-10-29 14:46:29,959] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20241014T000000, start_date=20241029T174629, end_date=20241029T174629
[2024-10-29 14:46:29,969] {standard_task_runner.py:92} ERROR - Failed to execute job 32 for task cria_pasta ('date_interval_end' is undefined; 109176)
[2024-10-29 14:46:30,005] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-10-29 14:46:30,026] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-29 14:50:16,985] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-10-14T00:00:00+00:00 [queued]>
[2024-10-29 14:50:16,989] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-10-14T00:00:00+00:00 [queued]>
[2024-10-29 14:50:16,990] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-10-29 14:50:16,990] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-10-29 14:50:16,990] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-10-29 14:50:17,001] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2024-10-14 00:00:00+00:00
[2024-10-29 14:50:17,004] {standard_task_runner.py:52} INFO - Started process 111020 to run task
[2024-10-29 14:50:17,005] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2024-10-14T00:00:00+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpt_bod369', '--error-file', '/tmp/tmps8hid0u1']
[2024-10-29 14:50:17,006] {standard_task_runner.py:80} INFO - Job 39: Subtask cria_pasta
[2024-10-29 14:50:17,030] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-10-14T00:00:00+00:00 [running]> on host LAPTOP-SNAE0A1O.
[2024-10-29 14:50:17,066] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2024-10-14T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-10-14T00:00:00+00:00
[2024-10-29 14:50:17,066] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-10-29 14:50:17,067] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/root/Documentos/airflow/semana=2024-10-21"']
[2024-10-29 14:50:17,072] {subprocess.py:85} INFO - Output:
[2024-10-29 14:50:17,074] {subprocess.py:96} INFO - Command exited with return code 0
[2024-10-29 14:50:17,090] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20241014T000000, start_date=20241029T175016, end_date=20241029T175017
[2024-10-29 14:50:17,138] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-10-29 14:50:17,160] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-29 14:53:44,417] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-10-14T00:00:00+00:00 [queued]>
[2024-10-29 14:53:44,421] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-10-14T00:00:00+00:00 [queued]>
[2024-10-29 14:53:44,421] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-10-29 14:53:44,421] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-10-29 14:53:44,421] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-10-29 14:53:44,433] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2024-10-14 00:00:00+00:00
[2024-10-29 14:53:44,435] {standard_task_runner.py:52} INFO - Started process 112740 to run task
[2024-10-29 14:53:44,437] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2024-10-14T00:00:00+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmp73okk17l', '--error-file', '/tmp/tmp2uv7wx97']
[2024-10-29 14:53:44,438] {standard_task_runner.py:80} INFO - Job 39: Subtask cria_pasta
[2024-10-29 14:53:44,462] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-10-14T00:00:00+00:00 [running]> on host LAPTOP-SNAE0A1O.
[2024-10-29 14:53:44,497] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2024-10-14T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-10-14T00:00:00+00:00
[2024-10-29 14:53:44,497] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-10-29 14:53:44,498] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/root/Documentos/airflow/semana=2024-10-21"']
[2024-10-29 14:53:44,503] {subprocess.py:85} INFO - Output:
[2024-10-29 14:53:44,505] {subprocess.py:96} INFO - Command exited with return code 0
[2024-10-29 14:53:44,520] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20241014T000000, start_date=20241029T175344, end_date=20241029T175344
[2024-10-29 14:53:44,569] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-10-29 14:53:44,589] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-29 14:56:50,294] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-10-14T00:00:00+00:00 [queued]>
[2024-10-29 14:56:50,299] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-10-14T00:00:00+00:00 [queued]>
[2024-10-29 14:56:50,299] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-10-29 14:56:50,299] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-10-29 14:56:50,299] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-10-29 14:56:50,311] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2024-10-14 00:00:00+00:00
[2024-10-29 14:56:50,314] {standard_task_runner.py:52} INFO - Started process 114278 to run task
[2024-10-29 14:56:50,316] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2024-10-14T00:00:00+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmp1wjbeusn', '--error-file', '/tmp/tmpgg6w97fc']
[2024-10-29 14:56:50,316] {standard_task_runner.py:80} INFO - Job 39: Subtask cria_pasta
[2024-10-29 14:56:50,341] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-10-14T00:00:00+00:00 [running]> on host LAPTOP-SNAE0A1O.
[2024-10-29 14:56:50,375] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2024-10-14T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-10-14T00:00:00+00:00
[2024-10-29 14:56:50,376] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-10-29 14:56:50,376] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/root/Documentos/airflow/semana=2024-10-21"']
[2024-10-29 14:56:50,382] {subprocess.py:85} INFO - Output:
[2024-10-29 14:56:50,383] {subprocess.py:96} INFO - Command exited with return code 0
[2024-10-29 14:56:50,398] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20241014T000000, start_date=20241029T175650, end_date=20241029T175650
[2024-10-29 14:56:50,449] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-10-29 14:56:50,467] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-29 15:02:43,741] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-10-14T00:00:00+00:00 [queued]>
[2024-10-29 15:02:43,745] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-10-14T00:00:00+00:00 [queued]>
[2024-10-29 15:02:43,745] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-10-29 15:02:43,745] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-10-29 15:02:43,745] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-10-29 15:02:43,757] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2024-10-14 00:00:00+00:00
[2024-10-29 15:02:43,759] {standard_task_runner.py:52} INFO - Started process 117104 to run task
[2024-10-29 15:02:43,761] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2024-10-14T00:00:00+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmptc0wzxvs', '--error-file', '/tmp/tmp9h467me5']
[2024-10-29 15:02:43,762] {standard_task_runner.py:80} INFO - Job 39: Subtask cria_pasta
[2024-10-29 15:02:43,787] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-10-14T00:00:00+00:00 [running]> on host LAPTOP-SNAE0A1O.
[2024-10-29 15:02:43,821] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2024-10-14T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-10-14T00:00:00+00:00
[2024-10-29 15:02:43,822] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-10-29 15:02:43,823] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/root/Documentos/airflow/semana=2024-10-21"']
[2024-10-29 15:02:43,827] {subprocess.py:85} INFO - Output:
[2024-10-29 15:02:43,829] {subprocess.py:96} INFO - Command exited with return code 0
[2024-10-29 15:02:43,845] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20241014T000000, start_date=20241029T180243, end_date=20241029T180243
[2024-10-29 15:02:43,893] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-10-29 15:02:43,912] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-29 15:05:37,917] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-10-14T00:00:00+00:00 [queued]>
[2024-10-29 15:05:37,921] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-10-14T00:00:00+00:00 [queued]>
[2024-10-29 15:05:37,922] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-10-29 15:05:37,922] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-10-29 15:05:37,922] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-10-29 15:05:37,933] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2024-10-14 00:00:00+00:00
[2024-10-29 15:05:37,935] {standard_task_runner.py:52} INFO - Started process 118577 to run task
[2024-10-29 15:05:37,937] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2024-10-14T00:00:00+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpf969rkbw', '--error-file', '/tmp/tmp_9q5cmli']
[2024-10-29 15:05:37,938] {standard_task_runner.py:80} INFO - Job 39: Subtask cria_pasta
[2024-10-29 15:05:37,970] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-10-14T00:00:00+00:00 [running]> on host LAPTOP-SNAE0A1O.
[2024-10-29 15:05:38,005] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2024-10-14T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-10-14T00:00:00+00:00
[2024-10-29 15:05:38,006] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-10-29 15:05:38,007] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/root/Documentos/airflow/semana=2024-10-21"']
[2024-10-29 15:05:38,013] {subprocess.py:85} INFO - Output:
[2024-10-29 15:05:38,014] {subprocess.py:96} INFO - Command exited with return code 0
[2024-10-29 15:05:38,030] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20241014T000000, start_date=20241029T180537, end_date=20241029T180538
[2024-10-29 15:05:38,069] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-10-29 15:05:38,089] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-29 15:11:03,924] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-10-14T00:00:00+00:00 [queued]>
[2024-10-29 15:11:03,929] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-10-14T00:00:00+00:00 [queued]>
[2024-10-29 15:11:03,929] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-10-29 15:11:03,929] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-10-29 15:11:03,929] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-10-29 15:11:03,941] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2024-10-14 00:00:00+00:00
[2024-10-29 15:11:03,943] {standard_task_runner.py:52} INFO - Started process 121199 to run task
[2024-10-29 15:11:03,945] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2024-10-14T00:00:00+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpbkyq879f', '--error-file', '/tmp/tmpajwe5iz_']
[2024-10-29 15:11:03,945] {standard_task_runner.py:80} INFO - Job 39: Subtask cria_pasta
[2024-10-29 15:11:03,970] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-10-14T00:00:00+00:00 [running]> on host LAPTOP-SNAE0A1O.
[2024-10-29 15:11:04,003] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2024-10-14T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-10-14T00:00:00+00:00
[2024-10-29 15:11:04,004] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-10-29 15:11:04,004] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/root/Documentos/airflow/semana=2024-10-21"']
[2024-10-29 15:11:04,010] {subprocess.py:85} INFO - Output:
[2024-10-29 15:11:04,011] {subprocess.py:96} INFO - Command exited with return code 0
[2024-10-29 15:11:04,026] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20241014T000000, start_date=20241029T181103, end_date=20241029T181104
[2024-10-29 15:11:04,077] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-10-29 15:11:04,097] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-29 15:14:29,221] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-10-14T00:00:00+00:00 [queued]>
[2024-10-29 15:14:29,226] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-10-14T00:00:00+00:00 [queued]>
[2024-10-29 15:14:29,226] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-10-29 15:14:29,226] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-10-29 15:14:29,226] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-10-29 15:14:29,238] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2024-10-14 00:00:00+00:00
[2024-10-29 15:14:29,241] {standard_task_runner.py:52} INFO - Started process 122902 to run task
[2024-10-29 15:14:29,242] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2024-10-14T00:00:00+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpowamb845', '--error-file', '/tmp/tmphn4wm5uw']
[2024-10-29 15:14:29,242] {standard_task_runner.py:80} INFO - Job 39: Subtask cria_pasta
[2024-10-29 15:14:29,268] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-10-14T00:00:00+00:00 [running]> on host LAPTOP-SNAE0A1O.
[2024-10-29 15:14:29,304] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2024-10-14T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-10-14T00:00:00+00:00
[2024-10-29 15:14:29,304] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-10-29 15:14:29,305] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/root/Documentos/airflow/semana=2024-10-21"']
[2024-10-29 15:14:29,310] {subprocess.py:85} INFO - Output:
[2024-10-29 15:14:29,311] {subprocess.py:96} INFO - Command exited with return code 0
[2024-10-29 15:14:29,326] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20241014T000000, start_date=20241029T181429, end_date=20241029T181429
[2024-10-29 15:14:29,375] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-10-29 15:14:29,393] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-29 19:04:43,045] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-10-14T00:00:00+00:00 [queued]>
[2024-10-29 19:04:43,049] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-10-14T00:00:00+00:00 [queued]>
[2024-10-29 19:04:43,049] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-10-29 19:04:43,049] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-10-29 19:04:43,049] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-10-29 19:04:43,063] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2024-10-14 00:00:00+00:00
[2024-10-29 19:04:43,066] {standard_task_runner.py:52} INFO - Started process 54275 to run task
[2024-10-29 19:04:43,067] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2024-10-14T00:00:00+00:00', '--job-id', '55', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmp87ycz7q0', '--error-file', '/tmp/tmpvstwdhjf']
[2024-10-29 19:04:43,068] {standard_task_runner.py:80} INFO - Job 55: Subtask cria_pasta
[2024-10-29 19:04:43,092] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-10-14T00:00:00+00:00 [running]> on host LAPTOP-SNAE0A1O.
[2024-10-29 19:04:43,130] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2024-10-14T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-10-14T00:00:00+00:00
[2024-10-29 19:04:43,131] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-10-29 19:04:43,132] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/root/Documentos/airflow/semana=2024-10-21"']
[2024-10-29 19:04:43,138] {subprocess.py:85} INFO - Output:
[2024-10-29 19:04:43,140] {subprocess.py:96} INFO - Command exited with return code 0
[2024-10-29 19:04:43,155] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20241014T000000, start_date=20241029T220443, end_date=20241029T220443
[2024-10-29 19:04:43,200] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-10-29 19:04:43,220] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
