[2024-10-29 14:39:23,736] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-10-21T00:00:00+00:00 [queued]>
[2024-10-29 14:39:23,740] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-10-21T00:00:00+00:00 [queued]>
[2024-10-29 14:39:23,740] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-10-29 14:39:23,740] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-10-29 14:39:23,740] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-10-29 14:39:23,751] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2024-10-21 00:00:00+00:00
[2024-10-29 14:39:23,754] {standard_task_runner.py:52} INFO - Started process 105810 to run task
[2024-10-29 14:39:23,756] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2024-10-21T00:00:00+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmp1ps1o8b7', '--error-file', '/tmp/tmpc52extz3']
[2024-10-29 14:39:23,756] {standard_task_runner.py:80} INFO - Job 33: Subtask cria_pasta
[2024-10-29 14:39:23,782] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-10-21T00:00:00+00:00 [running]> on host LAPTOP-SNAE0A1O.
[2024-10-29 14:39:23,798] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1451, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1555, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2212, in render_templates
    rendered_task = self.task.render_template_fields(context)
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 1185, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/utils/session.py", line 71, in wrapper
    return func(*args, session=session, **kwargs)
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 344, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 387, in render_template
    template = jinja_env.from_string(value)
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1092, in from_string
    return cls.from_code(self, self.compile(source), gs, None)
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/jinja2/environment.py", line 757, in compile
    self.handle_exception(source=source_hint)
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<unknown>", line 1, in template
jinja2.exceptions.TemplateSyntaxError: unexpected '%'
[2024-10-29 14:39:23,801] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20241021T000000, start_date=20241029T173923, end_date=20241029T173923
[2024-10-29 14:39:23,811] {standard_task_runner.py:92} ERROR - Failed to execute job 33 for task cria_pasta (unexpected '%'; 105810)
[2024-10-29 14:39:23,848] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-10-29 14:39:23,869] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-29 14:43:46,834] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-10-21T00:00:00+00:00 [queued]>
[2024-10-29 14:43:46,838] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-10-21T00:00:00+00:00 [queued]>
[2024-10-29 14:43:46,838] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-10-29 14:43:46,838] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-10-29 14:43:46,838] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-10-29 14:43:46,849] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2024-10-21 00:00:00+00:00
[2024-10-29 14:43:46,852] {standard_task_runner.py:52} INFO - Started process 107886 to run task
[2024-10-29 14:43:46,854] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2024-10-21T00:00:00+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmp5v3_63a5', '--error-file', '/tmp/tmpx9lx6v9b']
[2024-10-29 14:43:46,854] {standard_task_runner.py:80} INFO - Job 33: Subtask cria_pasta
[2024-10-29 14:43:46,879] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-10-21T00:00:00+00:00 [running]> on host LAPTOP-SNAE0A1O.
[2024-10-29 14:43:46,897] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1451, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1555, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2212, in render_templates
    rendered_task = self.task.render_template_fields(context)
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 1185, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/utils/session.py", line 71, in wrapper
    return func(*args, session=session, **kwargs)
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 344, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 391, in render_template
    return render_template_to_string(template, context)
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/utils/helpers.py", line 296, in render_template_to_string
    return render_template(template, context, native=False)
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/utils/helpers.py", line 291, in render_template
    return "".join(nodes)
  File "<template>", line 13, in root
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/jinja2/sandbox.py", line 326, in getattr
    value = getattr(obj, attribute)
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/jinja2/runtime.py", line 910, in __getattr__
    return self._fail_with_undefined_error()
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/jinja2/runtime.py", line 903, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'date_interval_end' is undefined
[2024-10-29 14:43:46,900] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20241021T000000, start_date=20241029T174346, end_date=20241029T174346
[2024-10-29 14:43:46,909] {standard_task_runner.py:92} ERROR - Failed to execute job 33 for task cria_pasta ('date_interval_end' is undefined; 107886)
[2024-10-29 14:43:46,946] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-10-29 14:43:46,967] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-29 14:46:31,359] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-10-21T00:00:00+00:00 [queued]>
[2024-10-29 14:46:31,363] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-10-21T00:00:00+00:00 [queued]>
[2024-10-29 14:46:31,363] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-10-29 14:46:31,363] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-10-29 14:46:31,363] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-10-29 14:46:31,374] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2024-10-21 00:00:00+00:00
[2024-10-29 14:46:31,377] {standard_task_runner.py:52} INFO - Started process 109205 to run task
[2024-10-29 14:46:31,378] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2024-10-21T00:00:00+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmp1d8bioki', '--error-file', '/tmp/tmpv_jzmwm0']
[2024-10-29 14:46:31,379] {standard_task_runner.py:80} INFO - Job 33: Subtask cria_pasta
[2024-10-29 14:46:31,404] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-10-21T00:00:00+00:00 [running]> on host LAPTOP-SNAE0A1O.
[2024-10-29 14:46:31,424] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1451, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1555, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2212, in render_templates
    rendered_task = self.task.render_template_fields(context)
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 1185, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/utils/session.py", line 71, in wrapper
    return func(*args, session=session, **kwargs)
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 344, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 391, in render_template
    return render_template_to_string(template, context)
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/utils/helpers.py", line 296, in render_template_to_string
    return render_template(template, context, native=False)
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/utils/helpers.py", line 291, in render_template
    return "".join(nodes)
  File "<template>", line 13, in root
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/jinja2/sandbox.py", line 326, in getattr
    value = getattr(obj, attribute)
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/jinja2/runtime.py", line 910, in __getattr__
    return self._fail_with_undefined_error()
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/jinja2/runtime.py", line 903, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'date_interval_end' is undefined
[2024-10-29 14:46:31,426] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20241021T000000, start_date=20241029T174631, end_date=20241029T174631
[2024-10-29 14:46:31,436] {standard_task_runner.py:92} ERROR - Failed to execute job 33 for task cria_pasta ('date_interval_end' is undefined; 109205)
[2024-10-29 14:46:31,471] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-10-29 14:46:31,492] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-29 14:50:21,785] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-10-21T00:00:00+00:00 [queued]>
[2024-10-29 14:50:21,789] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-10-21T00:00:00+00:00 [queued]>
[2024-10-29 14:50:21,790] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-10-29 14:50:21,790] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-10-29 14:50:21,790] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-10-29 14:50:21,801] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2024-10-21 00:00:00+00:00
[2024-10-29 14:50:21,803] {standard_task_runner.py:52} INFO - Started process 111107 to run task
[2024-10-29 14:50:21,805] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2024-10-21T00:00:00+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpf986kaob', '--error-file', '/tmp/tmp1ozdtipn']
[2024-10-29 14:50:21,805] {standard_task_runner.py:80} INFO - Job 42: Subtask cria_pasta
[2024-10-29 14:50:21,831] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-10-21T00:00:00+00:00 [running]> on host LAPTOP-SNAE0A1O.
[2024-10-29 14:50:21,873] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2024-10-21T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-10-21T00:00:00+00:00
[2024-10-29 14:50:21,873] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-10-29 14:50:21,874] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/root/Documentos/airflow/semana=2024-10-28"']
[2024-10-29 14:50:21,879] {subprocess.py:85} INFO - Output:
[2024-10-29 14:50:21,881] {subprocess.py:96} INFO - Command exited with return code 0
[2024-10-29 14:50:21,896] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20241021T000000, start_date=20241029T175021, end_date=20241029T175021
[2024-10-29 14:50:21,938] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-10-29 14:50:21,956] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-29 14:53:49,334] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-10-21T00:00:00+00:00 [queued]>
[2024-10-29 14:53:49,338] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-10-21T00:00:00+00:00 [queued]>
[2024-10-29 14:53:49,338] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-10-29 14:53:49,338] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-10-29 14:53:49,338] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-10-29 14:53:49,349] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2024-10-21 00:00:00+00:00
[2024-10-29 14:53:49,352] {standard_task_runner.py:52} INFO - Started process 112828 to run task
[2024-10-29 14:53:49,354] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2024-10-21T00:00:00+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpkk8ic8zc', '--error-file', '/tmp/tmppil71b2u']
[2024-10-29 14:53:49,354] {standard_task_runner.py:80} INFO - Job 42: Subtask cria_pasta
[2024-10-29 14:53:49,379] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-10-21T00:00:00+00:00 [running]> on host LAPTOP-SNAE0A1O.
[2024-10-29 14:53:49,413] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2024-10-21T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-10-21T00:00:00+00:00
[2024-10-29 14:53:49,414] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-10-29 14:53:49,414] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/root/Documentos/airflow/semana=2024-10-28"']
[2024-10-29 14:53:49,420] {subprocess.py:85} INFO - Output:
[2024-10-29 14:53:49,421] {subprocess.py:96} INFO - Command exited with return code 0
[2024-10-29 14:53:49,436] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20241021T000000, start_date=20241029T175349, end_date=20241029T175349
[2024-10-29 14:53:49,486] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-10-29 14:53:49,504] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-29 14:56:55,193] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-10-21T00:00:00+00:00 [queued]>
[2024-10-29 14:56:55,198] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-10-21T00:00:00+00:00 [queued]>
[2024-10-29 14:56:55,198] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-10-29 14:56:55,198] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-10-29 14:56:55,198] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-10-29 14:56:55,209] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2024-10-21 00:00:00+00:00
[2024-10-29 14:56:55,212] {standard_task_runner.py:52} INFO - Started process 114368 to run task
[2024-10-29 14:56:55,214] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2024-10-21T00:00:00+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmp9ifwd3uf', '--error-file', '/tmp/tmpa1kfryo6']
[2024-10-29 14:56:55,214] {standard_task_runner.py:80} INFO - Job 42: Subtask cria_pasta
[2024-10-29 14:56:55,240] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-10-21T00:00:00+00:00 [running]> on host LAPTOP-SNAE0A1O.
[2024-10-29 14:56:55,277] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2024-10-21T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-10-21T00:00:00+00:00
[2024-10-29 14:56:55,277] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-10-29 14:56:55,278] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/root/Documentos/airflow/semana=2024-10-28"']
[2024-10-29 14:56:55,283] {subprocess.py:85} INFO - Output:
[2024-10-29 14:56:55,285] {subprocess.py:96} INFO - Command exited with return code 0
[2024-10-29 14:56:55,301] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20241021T000000, start_date=20241029T175655, end_date=20241029T175655
[2024-10-29 14:56:55,346] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-10-29 14:56:55,367] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-29 15:02:48,595] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-10-21T00:00:00+00:00 [queued]>
[2024-10-29 15:02:48,599] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-10-21T00:00:00+00:00 [queued]>
[2024-10-29 15:02:48,599] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-10-29 15:02:48,599] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-10-29 15:02:48,599] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-10-29 15:02:48,612] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2024-10-21 00:00:00+00:00
[2024-10-29 15:02:48,615] {standard_task_runner.py:52} INFO - Started process 117196 to run task
[2024-10-29 15:02:48,617] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2024-10-21T00:00:00+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpzqtc05ve', '--error-file', '/tmp/tmpfp_7mh2_']
[2024-10-29 15:02:48,617] {standard_task_runner.py:80} INFO - Job 42: Subtask cria_pasta
[2024-10-29 15:02:48,641] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-10-21T00:00:00+00:00 [running]> on host LAPTOP-SNAE0A1O.
[2024-10-29 15:02:48,676] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2024-10-21T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-10-21T00:00:00+00:00
[2024-10-29 15:02:48,677] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-10-29 15:02:48,678] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/root/Documentos/airflow/semana=2024-10-28"']
[2024-10-29 15:02:48,683] {subprocess.py:85} INFO - Output:
[2024-10-29 15:02:48,685] {subprocess.py:96} INFO - Command exited with return code 0
[2024-10-29 15:02:48,701] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20241021T000000, start_date=20241029T180248, end_date=20241029T180248
[2024-10-29 15:02:48,749] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-10-29 15:02:48,769] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-29 15:05:42,742] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-10-21T00:00:00+00:00 [queued]>
[2024-10-29 15:05:42,746] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-10-21T00:00:00+00:00 [queued]>
[2024-10-29 15:05:42,746] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-10-29 15:05:42,747] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-10-29 15:05:42,747] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-10-29 15:05:42,757] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2024-10-21 00:00:00+00:00
[2024-10-29 15:05:42,760] {standard_task_runner.py:52} INFO - Started process 118665 to run task
[2024-10-29 15:05:42,761] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2024-10-21T00:00:00+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmp181qya35', '--error-file', '/tmp/tmpheww98wk']
[2024-10-29 15:05:42,762] {standard_task_runner.py:80} INFO - Job 42: Subtask cria_pasta
[2024-10-29 15:05:42,786] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-10-21T00:00:00+00:00 [running]> on host LAPTOP-SNAE0A1O.
[2024-10-29 15:05:42,820] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2024-10-21T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-10-21T00:00:00+00:00
[2024-10-29 15:05:42,821] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-10-29 15:05:42,821] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/root/Documentos/airflow/semana=2024-10-28"']
[2024-10-29 15:05:42,827] {subprocess.py:85} INFO - Output:
[2024-10-29 15:05:42,828] {subprocess.py:96} INFO - Command exited with return code 0
[2024-10-29 15:05:42,843] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20241021T000000, start_date=20241029T180542, end_date=20241029T180542
[2024-10-29 15:05:42,894] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-10-29 15:05:42,913] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-29 15:11:10,280] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-10-21T00:00:00+00:00 [queued]>
[2024-10-29 15:11:10,284] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-10-21T00:00:00+00:00 [queued]>
[2024-10-29 15:11:10,284] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-10-29 15:11:10,284] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-10-29 15:11:10,284] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-10-29 15:11:10,302] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2024-10-21 00:00:00+00:00
[2024-10-29 15:11:10,305] {standard_task_runner.py:52} INFO - Started process 121297 to run task
[2024-10-29 15:11:10,307] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2024-10-21T00:00:00+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpyzu_2qaz', '--error-file', '/tmp/tmpt44s9_bg']
[2024-10-29 15:11:10,307] {standard_task_runner.py:80} INFO - Job 42: Subtask cria_pasta
[2024-10-29 15:11:10,332] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-10-21T00:00:00+00:00 [running]> on host LAPTOP-SNAE0A1O.
[2024-10-29 15:11:10,371] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2024-10-21T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-10-21T00:00:00+00:00
[2024-10-29 15:11:10,371] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-10-29 15:11:10,372] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/root/Documentos/airflow/semana=2024-10-28"']
[2024-10-29 15:11:10,377] {subprocess.py:85} INFO - Output:
[2024-10-29 15:11:10,378] {subprocess.py:96} INFO - Command exited with return code 0
[2024-10-29 15:11:10,394] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20241021T000000, start_date=20241029T181110, end_date=20241029T181110
[2024-10-29 15:11:10,439] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-10-29 15:11:10,458] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-29 15:14:35,551] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-10-21T00:00:00+00:00 [queued]>
[2024-10-29 15:14:35,555] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-10-21T00:00:00+00:00 [queued]>
[2024-10-29 15:14:35,555] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-10-29 15:14:35,555] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-10-29 15:14:35,555] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-10-29 15:14:35,566] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2024-10-21 00:00:00+00:00
[2024-10-29 15:14:35,569] {standard_task_runner.py:52} INFO - Started process 123000 to run task
[2024-10-29 15:14:35,571] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2024-10-21T00:00:00+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmph1rz78ft', '--error-file', '/tmp/tmppw335l_5']
[2024-10-29 15:14:35,571] {standard_task_runner.py:80} INFO - Job 42: Subtask cria_pasta
[2024-10-29 15:14:35,598] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-10-21T00:00:00+00:00 [running]> on host LAPTOP-SNAE0A1O.
[2024-10-29 15:14:35,635] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2024-10-21T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-10-21T00:00:00+00:00
[2024-10-29 15:14:35,635] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-10-29 15:14:35,636] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/root/Documentos/airflow/semana=2024-10-28"']
[2024-10-29 15:14:35,642] {subprocess.py:85} INFO - Output:
[2024-10-29 15:14:35,643] {subprocess.py:96} INFO - Command exited with return code 0
[2024-10-29 15:14:35,659] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20241021T000000, start_date=20241029T181435, end_date=20241029T181435
[2024-10-29 15:14:35,703] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-10-29 15:14:35,723] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-29 19:04:50,621] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-10-21T00:00:00+00:00 [queued]>
[2024-10-29 19:04:50,626] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-10-21T00:00:00+00:00 [queued]>
[2024-10-29 19:04:50,626] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-10-29 19:04:50,626] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-10-29 19:04:50,626] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-10-29 19:04:50,638] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2024-10-21 00:00:00+00:00
[2024-10-29 19:04:50,641] {standard_task_runner.py:52} INFO - Started process 54373 to run task
[2024-10-29 19:04:50,643] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2024-10-21T00:00:00+00:00', '--job-id', '58', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpwxr8h849', '--error-file', '/tmp/tmp63u3c0bd']
[2024-10-29 19:04:50,643] {standard_task_runner.py:80} INFO - Job 58: Subtask cria_pasta
[2024-10-29 19:04:50,670] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-10-21T00:00:00+00:00 [running]> on host LAPTOP-SNAE0A1O.
[2024-10-29 19:04:50,708] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2024-10-21T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-10-21T00:00:00+00:00
[2024-10-29 19:04:50,709] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-10-29 19:04:50,710] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/root/Documentos/airflow/semana=2024-10-28"']
[2024-10-29 19:04:50,715] {subprocess.py:85} INFO - Output:
[2024-10-29 19:04:50,717] {subprocess.py:96} INFO - Command exited with return code 0
[2024-10-29 19:04:50,733] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20241021T000000, start_date=20241029T220450, end_date=20241029T220450
[2024-10-29 19:04:50,775] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-10-29 19:04:50,796] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
