[2024-10-29 14:39:18,306] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-10-07T00:00:00+00:00 [queued]>
[2024-10-29 14:39:18,309] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-10-07T00:00:00+00:00 [queued]>
[2024-10-29 14:39:18,309] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-10-29 14:39:18,309] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-10-29 14:39:18,310] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-10-29 14:39:18,323] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2024-10-07 00:00:00+00:00
[2024-10-29 14:39:18,326] {standard_task_runner.py:52} INFO - Started process 105744 to run task
[2024-10-29 14:39:18,328] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2024-10-07T00:00:00+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmps_nk6pjh', '--error-file', '/tmp/tmpz6pdltn_']
[2024-10-29 14:39:18,329] {standard_task_runner.py:80} INFO - Job 31: Subtask cria_pasta
[2024-10-29 14:39:18,356] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-10-07T00:00:00+00:00 [running]> on host LAPTOP-SNAE0A1O.
[2024-10-29 14:39:18,374] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1451, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1555, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2212, in render_templates
    rendered_task = self.task.render_template_fields(context)
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 1185, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/utils/session.py", line 71, in wrapper
    return func(*args, session=session, **kwargs)
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 344, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 387, in render_template
    template = jinja_env.from_string(value)
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1092, in from_string
    return cls.from_code(self, self.compile(source), gs, None)
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/jinja2/environment.py", line 757, in compile
    self.handle_exception(source=source_hint)
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<unknown>", line 1, in template
jinja2.exceptions.TemplateSyntaxError: unexpected '%'
[2024-10-29 14:39:18,377] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20241007T000000, start_date=20241029T173918, end_date=20241029T173918
[2024-10-29 14:39:18,387] {standard_task_runner.py:92} ERROR - Failed to execute job 31 for task cria_pasta (unexpected '%'; 105744)
[2024-10-29 14:39:18,420] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-10-29 14:39:18,443] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-29 14:43:43,819] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-10-07T00:00:00+00:00 [queued]>
[2024-10-29 14:43:43,824] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-10-07T00:00:00+00:00 [queued]>
[2024-10-29 14:43:43,824] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-10-29 14:43:43,824] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-10-29 14:43:43,824] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-10-29 14:43:43,835] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2024-10-07 00:00:00+00:00
[2024-10-29 14:43:43,839] {standard_task_runner.py:52} INFO - Started process 107829 to run task
[2024-10-29 14:43:43,840] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2024-10-07T00:00:00+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpmqrncz4b', '--error-file', '/tmp/tmpi16cybvq']
[2024-10-29 14:43:43,840] {standard_task_runner.py:80} INFO - Job 31: Subtask cria_pasta
[2024-10-29 14:43:43,865] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-10-07T00:00:00+00:00 [running]> on host LAPTOP-SNAE0A1O.
[2024-10-29 14:43:43,884] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1451, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1555, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2212, in render_templates
    rendered_task = self.task.render_template_fields(context)
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 1185, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/utils/session.py", line 71, in wrapper
    return func(*args, session=session, **kwargs)
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 344, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 391, in render_template
    return render_template_to_string(template, context)
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/utils/helpers.py", line 296, in render_template_to_string
    return render_template(template, context, native=False)
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/utils/helpers.py", line 291, in render_template
    return "".join(nodes)
  File "<template>", line 13, in root
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/jinja2/sandbox.py", line 326, in getattr
    value = getattr(obj, attribute)
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/jinja2/runtime.py", line 910, in __getattr__
    return self._fail_with_undefined_error()
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/jinja2/runtime.py", line 903, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'date_interval_end' is undefined
[2024-10-29 14:43:43,887] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20241007T000000, start_date=20241029T174343, end_date=20241029T174343
[2024-10-29 14:43:43,897] {standard_task_runner.py:92} ERROR - Failed to execute job 31 for task cria_pasta ('date_interval_end' is undefined; 107829)
[2024-10-29 14:43:43,933] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-10-29 14:43:43,953] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-29 14:46:27,394] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-10-07T00:00:00+00:00 [queued]>
[2024-10-29 14:46:27,399] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-10-07T00:00:00+00:00 [queued]>
[2024-10-29 14:46:27,399] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-10-29 14:46:27,399] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-10-29 14:46:27,399] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-10-29 14:46:27,411] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2024-10-07 00:00:00+00:00
[2024-10-29 14:46:27,413] {standard_task_runner.py:52} INFO - Started process 109139 to run task
[2024-10-29 14:46:27,415] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2024-10-07T00:00:00+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpvepgimaz', '--error-file', '/tmp/tmpxrih9f17']
[2024-10-29 14:46:27,416] {standard_task_runner.py:80} INFO - Job 31: Subtask cria_pasta
[2024-10-29 14:46:27,440] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-10-07T00:00:00+00:00 [running]> on host LAPTOP-SNAE0A1O.
[2024-10-29 14:46:27,458] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1451, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1555, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2212, in render_templates
    rendered_task = self.task.render_template_fields(context)
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 1185, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/utils/session.py", line 71, in wrapper
    return func(*args, session=session, **kwargs)
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 344, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 391, in render_template
    return render_template_to_string(template, context)
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/utils/helpers.py", line 296, in render_template_to_string
    return render_template(template, context, native=False)
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/utils/helpers.py", line 291, in render_template
    return "".join(nodes)
  File "<template>", line 13, in root
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/jinja2/sandbox.py", line 326, in getattr
    value = getattr(obj, attribute)
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/jinja2/runtime.py", line 910, in __getattr__
    return self._fail_with_undefined_error()
  File "/root/Documentos/airflow/venv/lib/python3.9/site-packages/jinja2/runtime.py", line 903, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'date_interval_end' is undefined
[2024-10-29 14:46:27,460] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20241007T000000, start_date=20241029T174627, end_date=20241029T174627
[2024-10-29 14:46:27,471] {standard_task_runner.py:92} ERROR - Failed to execute job 31 for task cria_pasta ('date_interval_end' is undefined; 109139)
[2024-10-29 14:46:27,507] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-10-29 14:46:27,528] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-29 14:50:14,533] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-10-07T00:00:00+00:00 [queued]>
[2024-10-29 14:50:14,537] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-10-07T00:00:00+00:00 [queued]>
[2024-10-29 14:50:14,537] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-10-29 14:50:14,537] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-10-29 14:50:14,538] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-10-29 14:50:14,549] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2024-10-07 00:00:00+00:00
[2024-10-29 14:50:14,551] {standard_task_runner.py:52} INFO - Started process 110960 to run task
[2024-10-29 14:50:14,553] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2024-10-07T00:00:00+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpw88uy3j2', '--error-file', '/tmp/tmp9y2n4rm6']
[2024-10-29 14:50:14,553] {standard_task_runner.py:80} INFO - Job 37: Subtask cria_pasta
[2024-10-29 14:50:14,578] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-10-07T00:00:00+00:00 [running]> on host LAPTOP-SNAE0A1O.
[2024-10-29 14:50:14,613] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2024-10-07T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-10-07T00:00:00+00:00
[2024-10-29 14:50:14,614] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-10-29 14:50:14,614] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/root/Documentos/airflow/semana=2024-10-14"']
[2024-10-29 14:50:14,620] {subprocess.py:85} INFO - Output:
[2024-10-29 14:50:14,622] {subprocess.py:96} INFO - Command exited with return code 0
[2024-10-29 14:50:14,637] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20241007T000000, start_date=20241029T175014, end_date=20241029T175014
[2024-10-29 14:50:14,685] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-10-29 14:50:14,704] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-29 14:53:41,925] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-10-07T00:00:00+00:00 [queued]>
[2024-10-29 14:53:41,930] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-10-07T00:00:00+00:00 [queued]>
[2024-10-29 14:53:41,930] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-10-29 14:53:41,930] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-10-29 14:53:41,930] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-10-29 14:53:41,941] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2024-10-07 00:00:00+00:00
[2024-10-29 14:53:41,943] {standard_task_runner.py:52} INFO - Started process 112688 to run task
[2024-10-29 14:53:41,945] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2024-10-07T00:00:00+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpkvsuugy8', '--error-file', '/tmp/tmpetpgedbv']
[2024-10-29 14:53:41,946] {standard_task_runner.py:80} INFO - Job 37: Subtask cria_pasta
[2024-10-29 14:53:41,969] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-10-07T00:00:00+00:00 [running]> on host LAPTOP-SNAE0A1O.
[2024-10-29 14:53:42,003] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2024-10-07T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-10-07T00:00:00+00:00
[2024-10-29 14:53:42,004] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-10-29 14:53:42,004] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/root/Documentos/airflow/semana=2024-10-14"']
[2024-10-29 14:53:42,010] {subprocess.py:85} INFO - Output:
[2024-10-29 14:53:42,011] {subprocess.py:96} INFO - Command exited with return code 0
[2024-10-29 14:53:42,026] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20241007T000000, start_date=20241029T175341, end_date=20241029T175342
[2024-10-29 14:53:42,077] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-10-29 14:53:42,096] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-29 14:56:46,304] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-10-07T00:00:00+00:00 [queued]>
[2024-10-29 14:56:46,309] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-10-07T00:00:00+00:00 [queued]>
[2024-10-29 14:56:46,309] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-10-29 14:56:46,309] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-10-29 14:56:46,309] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-10-29 14:56:46,321] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2024-10-07 00:00:00+00:00
[2024-10-29 14:56:46,323] {standard_task_runner.py:52} INFO - Started process 114227 to run task
[2024-10-29 14:56:46,325] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2024-10-07T00:00:00+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpo8cw0cjk', '--error-file', '/tmp/tmpawwnkflf']
[2024-10-29 14:56:46,325] {standard_task_runner.py:80} INFO - Job 37: Subtask cria_pasta
[2024-10-29 14:56:46,350] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-10-07T00:00:00+00:00 [running]> on host LAPTOP-SNAE0A1O.
[2024-10-29 14:56:46,385] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2024-10-07T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-10-07T00:00:00+00:00
[2024-10-29 14:56:46,386] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-10-29 14:56:46,386] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/root/Documentos/airflow/semana=2024-10-14"']
[2024-10-29 14:56:46,392] {subprocess.py:85} INFO - Output:
[2024-10-29 14:56:46,393] {subprocess.py:96} INFO - Command exited with return code 0
[2024-10-29 14:56:46,409] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20241007T000000, start_date=20241029T175646, end_date=20241029T175646
[2024-10-29 14:56:46,458] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-10-29 14:56:46,476] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-29 15:02:41,269] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-10-07T00:00:00+00:00 [queued]>
[2024-10-29 15:02:41,273] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-10-07T00:00:00+00:00 [queued]>
[2024-10-29 15:02:41,273] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-10-29 15:02:41,273] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-10-29 15:02:41,273] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-10-29 15:02:41,284] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2024-10-07 00:00:00+00:00
[2024-10-29 15:02:41,287] {standard_task_runner.py:52} INFO - Started process 117050 to run task
[2024-10-29 15:02:41,289] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2024-10-07T00:00:00+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpeh1abrtw', '--error-file', '/tmp/tmpb3q755ci']
[2024-10-29 15:02:41,289] {standard_task_runner.py:80} INFO - Job 37: Subtask cria_pasta
[2024-10-29 15:02:41,314] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-10-07T00:00:00+00:00 [running]> on host LAPTOP-SNAE0A1O.
[2024-10-29 15:02:41,348] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2024-10-07T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-10-07T00:00:00+00:00
[2024-10-29 15:02:41,349] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-10-29 15:02:41,349] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/root/Documentos/airflow/semana=2024-10-14"']
[2024-10-29 15:02:41,355] {subprocess.py:85} INFO - Output:
[2024-10-29 15:02:41,357] {subprocess.py:96} INFO - Command exited with return code 0
[2024-10-29 15:02:41,373] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20241007T000000, start_date=20241029T180241, end_date=20241029T180241
[2024-10-29 15:02:41,421] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-10-29 15:02:41,440] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-29 15:05:35,462] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-10-07T00:00:00+00:00 [queued]>
[2024-10-29 15:05:35,466] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-10-07T00:00:00+00:00 [queued]>
[2024-10-29 15:05:35,466] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-10-29 15:05:35,466] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-10-29 15:05:35,466] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-10-29 15:05:35,478] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2024-10-07 00:00:00+00:00
[2024-10-29 15:05:35,480] {standard_task_runner.py:52} INFO - Started process 118519 to run task
[2024-10-29 15:05:35,482] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2024-10-07T00:00:00+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpc1i7y26q', '--error-file', '/tmp/tmpfge9umol']
[2024-10-29 15:05:35,482] {standard_task_runner.py:80} INFO - Job 37: Subtask cria_pasta
[2024-10-29 15:05:35,507] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-10-07T00:00:00+00:00 [running]> on host LAPTOP-SNAE0A1O.
[2024-10-29 15:05:35,540] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2024-10-07T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-10-07T00:00:00+00:00
[2024-10-29 15:05:35,541] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-10-29 15:05:35,541] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/root/Documentos/airflow/semana=2024-10-14"']
[2024-10-29 15:05:35,546] {subprocess.py:85} INFO - Output:
[2024-10-29 15:05:35,548] {subprocess.py:96} INFO - Command exited with return code 0
[2024-10-29 15:05:35,563] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20241007T000000, start_date=20241029T180535, end_date=20241029T180535
[2024-10-29 15:05:35,615] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-10-29 15:05:35,633] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-29 15:11:00,676] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-10-07T00:00:00+00:00 [queued]>
[2024-10-29 15:11:00,681] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-10-07T00:00:00+00:00 [queued]>
[2024-10-29 15:11:00,681] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-10-29 15:11:00,681] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-10-29 15:11:00,681] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-10-29 15:11:00,692] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2024-10-07 00:00:00+00:00
[2024-10-29 15:11:00,694] {standard_task_runner.py:52} INFO - Started process 121142 to run task
[2024-10-29 15:11:00,696] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2024-10-07T00:00:00+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpisyr7nd4', '--error-file', '/tmp/tmphmd_fssq']
[2024-10-29 15:11:00,696] {standard_task_runner.py:80} INFO - Job 37: Subtask cria_pasta
[2024-10-29 15:11:00,722] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-10-07T00:00:00+00:00 [running]> on host LAPTOP-SNAE0A1O.
[2024-10-29 15:11:00,759] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2024-10-07T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-10-07T00:00:00+00:00
[2024-10-29 15:11:00,760] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-10-29 15:11:00,760] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/root/Documentos/airflow/semana=2024-10-14"']
[2024-10-29 15:11:00,765] {subprocess.py:85} INFO - Output:
[2024-10-29 15:11:00,767] {subprocess.py:96} INFO - Command exited with return code 0
[2024-10-29 15:11:00,782] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20241007T000000, start_date=20241029T181100, end_date=20241029T181100
[2024-10-29 15:11:00,828] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-10-29 15:11:00,847] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-29 15:14:25,966] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-10-07T00:00:00+00:00 [queued]>
[2024-10-29 15:14:25,970] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-10-07T00:00:00+00:00 [queued]>
[2024-10-29 15:14:25,970] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-10-29 15:14:25,970] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-10-29 15:14:25,970] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-10-29 15:14:25,981] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2024-10-07 00:00:00+00:00
[2024-10-29 15:14:25,984] {standard_task_runner.py:52} INFO - Started process 122840 to run task
[2024-10-29 15:14:25,985] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2024-10-07T00:00:00+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpj2j_7rfk', '--error-file', '/tmp/tmp1iys_vcm']
[2024-10-29 15:14:25,985] {standard_task_runner.py:80} INFO - Job 37: Subtask cria_pasta
[2024-10-29 15:14:26,009] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-10-07T00:00:00+00:00 [running]> on host LAPTOP-SNAE0A1O.
[2024-10-29 15:14:26,043] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2024-10-07T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-10-07T00:00:00+00:00
[2024-10-29 15:14:26,044] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-10-29 15:14:26,044] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/root/Documentos/airflow/semana=2024-10-14"']
[2024-10-29 15:14:26,050] {subprocess.py:85} INFO - Output:
[2024-10-29 15:14:26,051] {subprocess.py:96} INFO - Command exited with return code 0
[2024-10-29 15:14:26,066] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20241007T000000, start_date=20241029T181425, end_date=20241029T181426
[2024-10-29 15:14:26,118] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-10-29 15:14:26,137] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-29 19:04:39,509] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-10-07T00:00:00+00:00 [queued]>
[2024-10-29 19:04:39,514] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-10-07T00:00:00+00:00 [queued]>
[2024-10-29 19:04:39,514] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-10-29 19:04:39,514] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-10-29 19:04:39,515] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-10-29 19:04:39,527] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2024-10-07 00:00:00+00:00
[2024-10-29 19:04:39,529] {standard_task_runner.py:52} INFO - Started process 54211 to run task
[2024-10-29 19:04:39,531] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2024-10-07T00:00:00+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpg9brnetj', '--error-file', '/tmp/tmpx6syo8vo']
[2024-10-29 19:04:39,532] {standard_task_runner.py:80} INFO - Job 53: Subtask cria_pasta
[2024-10-29 19:04:39,555] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2024-10-07T00:00:00+00:00 [running]> on host LAPTOP-SNAE0A1O.
[2024-10-29 19:04:39,591] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2024-10-07T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-10-07T00:00:00+00:00
[2024-10-29 19:04:39,591] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-10-29 19:04:39,592] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/root/Documentos/airflow/semana=2024-10-14"']
[2024-10-29 19:04:39,598] {subprocess.py:85} INFO - Output:
[2024-10-29 19:04:39,600] {subprocess.py:96} INFO - Command exited with return code 0
[2024-10-29 19:04:39,615] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20241007T000000, start_date=20241029T220439, end_date=20241029T220439
[2024-10-29 19:04:39,664] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-10-29 19:04:39,682] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
